## Configuracion de Spring
spring:
  application:
    name: ms-reserva
  datasource:
    url: jdbc:postgresql://localhost:5432/movieoperaciondb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8087
  
## Configuracion secundaria (custom)
getPelicula:
  url: http://ms-pelicula/peliculas/%s